name: clean_ajax
version: 0.4.12
author: Clean Team <clean@vacuumlabs.com>
description: Data transport layer for Clean framework.
homepage: http://cleandart.github.io/clean_ajax/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
documentation: http://cleandart.github.io/clean_ajax/
dependencies:
  browser: '>=0.9.0 <0.10.0'
  clean_backend: '>=0.2.0 <0.3.0'
  http_server: '>=0.9.0 <0.10.0'
  logging: any
dev_dependencies:
  hop: any
  unittest: '>=0.10.0'
