name: clean_ajax
version: 0.4.24
author: Clean Team <clean@vacuumlabs.com>
description: Data transport layer for Clean framework.
homepage: http://cleandart.github.io/clean_ajax/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.11.0'
  clean_backend: '>=0.5.5 <0.6.0'
  clean_logging: any
  http_server: '>=0.9.0 <0.10.0'
  uuid: any
dev_dependencies:
  hop: any
  unittest: '>=0.10.0 < 0.11.0'
