name: clean_ajax
author: VacuumLabs s.r.o.
description: Part of the clean.dart framework.
dependencies:
  browser: any
  clean_backend:
    git: https://github.com/cleandart/clean_backend
  http_server: any
dev_dependencies:
  unittest: any
